#!/usr/bin/env python

import tkinter
import time
from time import strftime
top = tkinter.Tk()
top.title('Clock')
top.resizable(True,True)
def time(): 
    string = strftime('%H:%M:%S %p') 
    clock.config(text = string) 
    clock.after(1000, time)
clock = tkinter.Label(top, font = ('arial', 40, 'bold'), background = 'white', foreground = 'black')
clock.pack(anchor = 'center')
time()

top.mainloop()
