#!/usr/bin/env python

import tkinter

from time import strftime
top = tkinter.Tk()
top.title('Python Clock')
top.resizable(0,0)
def time(): 
    string = strftime('%H:%M:%S %p') 
    clock.config(text = string) 
    clock.after(1000, time)
clock = tkinter.Label(top, font = ('arial', 40, 'bold'), background = 'white', foreground = 'black')
